### ISSUE TITLE
REQUEST: include `ditsuke/amibot` as a community project under `asetalias` :octocat: 

### ISSUE THREAD

**Issue by ditsuke** [asetalias/org#1]
## About

Amibot is a WhatsApp bot to interface with the Amizone student portal. The project is coded in JavaScript augmented with types through JSDOCs and type declaration (`d.ts`) files.

- Project link: https://github.com/ditsuke/amibot

## Why it should be included

Amibot has been developed by me and @azazz3L, both ALiAS members. With Amizone being of high interest to Amity students where ALiAS is based and the project being written in JavaScript, a popular and easy to learn language, I believe it'll be a great asset for the ALiAS community to collectively maintain and improve the project. It could even be used as a starter project to help people learn about JavaScript, rudimentary backend development and MongoDB besides dealing with a developer-unfriendly platform like https://developers.facebook.com! :laughing: 
Amibot can also serve as a promotion medium for the club itself since it'll be a high visibility project within the university, given the nigh irreplaceable nature of the portal and the barrier of usability of other official and unofficial ways to access the portal.

**Comment by ObsidianMaximus** [comment]
+1

**Comment by ditsuke** [comment]
Included!
