### ISSUE TITLE
REQUEST: New membership for ObsidianMaximus

### ISSUE THREAD

**Issue by ObsidianMaximus** [asetalias/org#4]
### GitHub Username

ObsidianMaximus

### Organization you are requesting membership in

asetalias

### Requirements

 - [x] I am actively contributing to 1 or more asetalias subprojects
 - [X] I am a student of Amity University Lucknow in B.Tech CSE
 - [X] I am willing to contribute to open source.

### List of contributions to the asetalias project

PRs at asetalias/amibot
asetalias/amibot/pull/14
asetalias/amibot/pull/24

Issues at asetalias/amibot [ addressed the issue ]
asetalias/amibot/issues/11
asetalias/amibot/issues/21

**Comment by ditsuke** [comment]
+1 from me

**Comment by achintya-7** [comment]
+1 from me

**Comment by ditsuke** [comment]
@ObsidianMaximus we've sent you an invite, welcome to the org!
