### ISSUE TITLE
REQUEST: New membership for Achintya

### ISSUE THREAD

**Issue by achintya-7** [asetalias/org#5]
## Github Username
achintya-7

## Organization you are requesting membership in
asetalias

## Requirements
- [x] I am actively contributing to 1 or more asetalias subprojects
- [x] I am a student of Amity University Noida in B.Tech CSE
- [x] I am willing to contribute to open source.

**Comment by ditsuke** [comment]
+1

**Comment by ChucklesDroid** [comment]
+1

**Comment by ditsuke** [comment]
Invited.
